parameters:
#    project_lunchtime.example.class: Project\LunchtimeBundle\Example

services:
#    project_lunchtime.example:
#        class: %project_lunchtime.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
